Fix genotype file path: disable tmp directory usage
ISSUE: Script trying to use files from /tmp/kellis/ukb21942/ which don't exist
  ERROR: Required file not found: /tmp/kellis/ukb21942/geno/ukb_genoHM3/ukb_genoHM3_bed.bed

ROOT CAUSE: use_tmp_geno was set to TRUE, but:
  - The cache.pgen.sh script copies pgen files, not bed files
  - Bed files (150GB) only exist in main data directory
  - Tmp strategy not needed for BOLT-LMM

FIX:
- Set use_tmp_geno=FALSE
- Simplified genotype file path logic
- Always use main data directory: /home/.../geno/ukb_genoHM3/ukb_genoHM3_bed
- Removed tmp directory conditional logic

The bed files are already in a high-performance location and
don't need to be copied to /tmp/.