Fix covariate specification: separate --covarCol for each variable
ERROR: Unable to find covariate sex,array

ISSUE: BOLT-LMM interpreted 'sex,array' as a SINGLE covariate name
       (looking for a column literally named 'sex,array')

BOLT-LMM SYNTAX for multiple categorical covariates:
  --covarCol=sex --covarCol=array
  NOT: --covarCol=sex,array

FIX in run_single_phenotype.sh:
- Changed covar_cols='sex,array' to covar_col_args='--covarCol=sex --covarCol=array'
- Use variable expansion:
- This creates two separate --covarCol arguments

Now BOLT-LMM will correctly parse:
  --covarCol=sex --covarCol=array

Instead of looking for a non-existent column named 'sex,array'.

The covariate file has both columns:
- sex (column 7)
- array (column 18)

They just need to be specified as separate arguments.